export const GET_ALL_GAME_TITLES = 'GET_ALL_GAME_TITLES'
export const GET_ALL_GAME_TITLES_SUCCESS = 'GET_ALL_GAME_TITLES_SUCCESS'
export const GET_ALL_QUESTIONS_BY_GAME_TILE = 'GET_ALL_QUESTIONS_BY_GAME_TILE'
export const GET_ALL_QUESTIONS_BY_GAME_TILE_SUCCESS = 'GET_ALL_QUESTIONS_BY_GAME_TILE_SUCCESS'
